AWSTemplateFormatVersion: '2010-09-09'
Description: Git repository (Phase 0)

Parameters:

  RepositoryName:
    Type: String
    Default: serverless-application

Resources:

  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
